kwek/views.py
# -*- coding: utf-8 -*-
#
# This file is part of Kwek Metrics.

"""Kwek Metric web app views."""

from urlparse import urljoin

from flask import render_template, flash, Blueprint
from flask.ext.wtf import Form
from wtforms import StringField
from wtforms.validators import DataRequired
from wtforms_alchemy import ModelForm

from api.hawkular import get_os_projects
from api.hawkular import get_metric
from database import db
from model import Service, Metric


blueprint = Blueprint('kwek', __name__,
                      template_folder='templates')


class ServiceForm(ModelForm, Form):
    """Handle subscribe form neatly with WTForms."""
    class Meta:
        model = Service

    name = StringField(u'Name:', validators=[DataRequired()])
    token = StringField(u'Service', validators=[DataRequired()])


class MetricForm(ModelForm, Form):
    """Handle subscribe form neatly with WTForms."""
    class Meta:
        model = Metric

    name = StringField(u'Name:', validators=[DataRequired()])
    api_name = StringField(u'Service', validators=[DataRequired()])


@blueprint.route('/', methods=['GET'])
def index():
    """Home page.
    Return a list of all the projects and it's top-level metrics.
    """
    s = Service.query.filter_by().first()
    try:
        projects = get_os_projects(
            urljoin(s.os_url, 'projects'),
            s.token)
    except ValueError as err:
        projects = {}
        flash(err.args)
    metrics = Metric.query.all()

    # Get the values for each metric, per project
    values = {}
    for project in projects:
        values[project['metadata']['name']] = {}
        try:
            for metric in metrics:
                v = get_metric(
                    urljoin(s.hwk_url, metric.endpoint),
                    project['metadata']['name'],
                    s.token,
                    metric.tag)
                values[project['metadata']['name']][metric.name] = v
        except ValueError as err:
            flash(project['metadata']['name'], err.message)
        except KeyError as err:
            flash(project['metadata']['name'], err.message)

    # Calculate the aggregated value of each metric
    totals = {}
    for metric in metrics:
        totals[metric.name] = 0
        for project in projects:
            # Get the last measure for the given metric
            last_measure = values[project['metadata']['name']][metric.name][0]
            # And sum it to our total per metric
            totals[metric.name] += last_measure['avg']

    return render_template(
        'stats.html',
        projects=projects,
        metrics=metrics,
        values=values,
        totals=totals)


@blueprint.route('/insert', methods=['GET'])
def insert():
    services = []
    for row in Service.query.all():
        services.append(row)
    return render_template(
        'insert_service.html',
        services=services)


@blueprint.route('/metrics/<project>', methods=['GET'])
def metrics(project):
    s = Service.query.filter_by().first()
    metrics = Metric.query.all()
    values = {}
    try:
        for metric in metrics:
            values[metric.name] = get_metric(
                urljoin(s.hwk_url, metric.endpoint),
                project,
                s.token,
                metric.tag)
    except ValueError as err:
        flash(err.args)
    return render_template('metrics.html',
                           project=project,
                           metrics=metrics,
                           values=values)


@blueprint.route('/insert', methods=['POST'])
def form_subscribe(data):
    """Handle subscription form submission."""
    try:
        # Try to find an existing user to update
        u = Service.query.filter_by(name=e_data['name']).first()
        # !TODO: This requires refactoring..
        if u:
            # Update Service
            u.name = e_data['name']
            u.token = e_data['token']
        else:
            # Create new Service
            u = Service(e_data['name'],
                     e_data['token'])
        db.session.add(u)
        db.session.commit()
        return True
    except Exception, e:
        print('form_subscribe():', str(e))
        flash(u'Saving to database failed.', 'Error')
        # Should return the errors (possibly duplicate or?)
        return False

kwek/views/metrics.py
# -*- coding: utf-8 -*-
#
# This file is part of Kwek Metrics.

"""Kwek Metrics Metric CRUD views."""

from flask import render_template, flash, Blueprint, request, redirect,\
    url_for, abort
from flask_wtf import Form
from wtforms import StringField, FloatField
from wtforms.validators import InputRequired
from wtforms_alchemy import ModelForm

from kwek.models import Metric
from kwek.database import db

blueprint = Blueprint('metrics', __name__,
                      template_folder='../templates/metrics/',
                      url_prefix='/metrics')


class MetricForm(ModelForm, Form):
    """Handle subscribe form neatly with WTForms."""
    class Meta:
        model = Metric

    name = StringField(u'Name:', validators=[InputRequired()])
    display_name = StringField(u'display_name:', validators=[InputRequired()])
    endpoint = StringField(u'endpoint:', validators=[InputRequired()])
    tag = StringField(u'tag:', validators=[InputRequired()])
    unit = StringField(u'unit:', validators=[InputRequired()])
    conversion = FloatField(u'conversion:', validators=[InputRequired()])
    maxvalue = FloatField(u'maxvalue:', validators=[InputRequired()])
    color = StringField(u'color:', validators=[InputRequired()])


def get(id):
    """Return a Metric."""
    result = Metric.query.get(id)
    if result:
        form = MetricForm(obj=result)
        metric = result.serialized
    else:
        abort(404)
    return render_template(
        'metrics/metric.html',
        metric=metric,
        form=form)


@blueprint.route('/', methods=['GET'])
def index():
    """Return a list of Metrics."""
    form = MetricForm()
    metrics = [metric.serialized for metric in Metric.query.all()]
    return render_template(
        'metrics/index.html',
        metrics=metrics,
        form=form)


@blueprint.route('/delete/<id>', methods=['POST'])
def delete(id):
    """Delete a Metric."""
    metric = Metric.query.get(id)
    if metric:
        try:
            db.session.delete(metric)
            db.session.commit()
            flash('Metric {0} deleted.'.format(metric.name), 'success')
        except Exception as e:
            db.session.rollback()
            flash('Error: {0}'.format(e.message), 'danger')
        finally:
            return redirect(url_for('.index'))
    else:
        abort(404)


@blueprint.route('/insert', methods=['POST'])
def insert():
    """Create a new Metric.

    Redirect to metrics/ page if succesfull,
    Return the metrics template with the errors otherwise
    """
    form = MetricForm(request.form)
    if form.validate():
        try:
            metric = Metric(
                form.name.data,
                form.display_name.data,
                form.endpoint.data,
                form.tag.data,
                form.unit.data,
                form.conversion.data,
                form.maxvalue.data,
                form.color.data)
            db.session.add(metric)
            db.session.commit()
            flash('Metric {0} created.'.format(form.name.data), 'success')
            return redirect(url_for('.index'))
        except Exception as e:
            db.session.rollback()
            flash('Error: {0}'.format(e.message), 'danger')

    # If the validation or insertion failed, present the errors w/ template
    return render_template('metrics/insert.html',
                           form=form)


@blueprint.route('/update/<id>', methods=['GET', 'POST'])
def update(id):
    """Update a Metric.

    redirect to metrics/ page if succesfull,
    return the metrics template with the errors otherwise
    """
    metric = Metric.query.get(id)
    if not metric:
        abort(404)

    if request.method == 'GET':
        form = MetricForm(obj=metric)
        return render_template(
            'metrics/update.html',
            metric=metric.serialized,
            form=form)

    elif request.method == 'POST':
        form = MetricForm(request.form)
        if form.validate():
            try:
                # Set the new fields
                # !TODO: is there a better way to do this?
                #        check form.data for a dict
                metric.name = form.name.data
                metric.display_name = form.display_name.data
                metric.endpoint = form.endpoint.data
                metric.tag = form.tag.data
                metric.unit = form.unit.data
                metric.conversion = form.conversion.data
                metric.maxvalue = form.maxvalue.data
                metric.color = form.color.data

                # Do the update
                db.session.add(metric)
                db.session.commit()
                flash('Metric {0} updated.'.format(form.name.data), 'success')
                return redirect(url_for('.index'))
            except Exception as e:
                db.session.rollback()
                flash('Error: {0}'.format(e.message), 'danger')

        # If the validation or insertion failed, present the errors w/ template
        return render_template('metrics/update.html',
                               metric=metric,
                               form=form)

kwek/views/views.py
# -*- coding: utf-8 -*-
#
# This file is part of Kwek Metrics.

"""Kwek Metric web app views."""

from urlparse import urljoin

from flask import render_template, flash, Blueprint, redirect, url_for
from requests import ConnectionError

from api.hawkular import get_os_projects
from api.hawkular import get_metric
from api.hawkular import get_metrics
from api.hawkular import APIAuthorizationError
from kwek.models import Service, Metric
from kwek.database import db

blueprint = Blueprint('kwek', __name__,
                      template_folder='../templates')


@blueprint.route('/', methods=['GET'])
def index():
    s = Service.query.filter_by().first()
    if s is None:
        flash('No Service found. Please add one below.', 'danger')
        return redirect(url_for('services.index'))
    try:
        projects = get_os_projects(
            urljoin(s.os_url, 'projects'),
            s.token)
    except (ValueError, AttributeError, ConnectionError) as err:
        projects = {}
        flash(err.message, 'danger')
    except APIAuthorizationError as err:
        flash(err.message, 'danger')
        return redirect(url_for('services.index'))
    # Build the query string
    # https://metrics.engint.openshift.com/hawkular/metrics/metrics/stats/query
    # {"tags":"descriptor_name:network/tx_rate|network/rx_rate,type:pod","buckets":"1"}
    # {"tags":"descriptor_name:memory/usage|cpu/usage_rate,type:pod_container","buckets":"1"}
    metrics_pod = {
        'endpoint': 'metrics/stats/query',
        'type': 'pod_container',
        'queries': [
            {'conversion': 9.53674e-07,
             'display_name': 'Memory Usage',
             'name': 'memory', 'color': 'blue', 'tag': 'memory/usage',
             'id': 2, 'unit': 'MiB', 'maxvalue': 836868241},
            {'conversion': 1.0,
             'display_name': 'CPU Usage',
             'name': 'cpu', 'color': 'red', 'tag': 'cpu/usage_rate',
             'id': 2, 'unit': 'Millicores', 'maxvalue': 0}
        ]
    }

    # Initialize the metric totals
    totals = {}
    # And the tags for the API request
    tags = []
    for metric in metrics_pod['queries']:
        tags.append(metric['tag'])
        totals[metric['tag']] = 0

    # Initialize metric values dict
    values = {}
    for p in projects:
        # Initialize metric for the project
        name = p['metadata']['name']
        values[name] = {'avg': {}}
        for tag in tags:
            # Initialize metric tags for the project
            values[name]['avg'][tag] = 0
            values[name][tag] = []
        try:
            # Get all the metrics for the project
            v = get_metrics(
                urljoin(s.hwk_url, metrics_pod['endpoint']),
                name,
                s.token,
                tags,
                'pod_container')  # !TODO: Replace with dynamic value
            # Iterate over the values
            for k, v in v['gauge'].iteritems():
                # Filter out `sti-build` values, e.g.:
                # "sti-build/7c197071-193a-11e7-8dbe-126ee6b1d97f/cpu/usage_rate"
                if k.partition('/')[0] != 'sti-build':
                    # Filter out Empty values
                    if v[0]['empty'] is False:
                        # Append each metric to its proper tag
                        for tag in tags:
                            if tag in k:
                                values[name][tag].append(v)
                                values[name][
                                    'avg'][tag] += v[0]['avg']
                                totals[tag] += v[0]['avg']
        except Exception as err:
            flash('{} - {}'.format(name, err.message), 'danger')

    for k, v in values.iteritems():
        pass

    return render_template(
        'index.html',
        projects=projects,
        values=values,
        metrics=metrics_pod['queries'],
        totals=totals)


@blueprint.route('/stats/<project>', methods=['GET'])
def stats(project):
    s = Service.query.filter_by().first()
    metrics = Metric.query.all()
    values = {}
    try:
        for metric in metrics:
            values[metric.name] = get_metric(
                urljoin(s.hwk_url, metric.endpoint),
                project,
                s.token,
                metric.tag)
    except (ValueError, ConnectionError) as err:
        flash(err.message, 'danger')
    return render_template('stats.html',
                           project=project,
                           metrics=metrics,
                           values=values)


default_service = {
    'name': 'OpenShift Dedicated',
    'token': 'this_will_be_updated',
    'hawkular': 'https://metrics.engint.openshift.com/hawkular/metrics/',
    'openshift': 'https://console.engint.openshift.com/oapi/v1/'
}


default_metrics = {
    'endpoint': 'metrics/stats/query',
    'type': 'pod_container',
    'queries': [
        {'conversion': 9.53674e-07,
         'display_name': 'Memory Usage',
         'name': 'memory', 'color': 'blue', 'tag': 'memory/usage',
         'id': 2, 'unit': 'MiB', 'max': 64424509440},
        {'conversion': 1.0,
         'display_name': 'CPU Usage',
         'name': 'cpu', 'color': 'red', 'tag': 'cpu/usage_rate',
         'id': 2, 'unit': 'Millicores', 'max': 16000}
    ]
}


@blueprint.route('/defaults')
def defaults():
    try:
        s = default_service
        service = Service(s['name'], s['token'],
                          s['hawkular'], s['openshift'])
        db.session.add(service)
        m0 = default_metrics['queries'][0]
        m1 = default_metrics['queries'][1]
        memory_metric = Metric(
            m0['name'],
            m0['display_name'],
            default_metrics['endpoint'],
            m0['tag'],
            m0['unit'],
            m0['conversion'],
            m0['max'],
            m0['color'])

        cpu_metric = Metric(
            m1['name'],
            m1['display_name'],
            default_metrics['endpoint'],
            m1['tag'],
            m1['unit'],
            m1['conversion'],
            m1['max'],
            m1['color'])

        db.session.add(memory_metric)
        db.session.add(cpu_metric)
        db.session.commit()
        flash('Service `{}` created. Please update the token.'.format(
            s['name']), 'success')
        flash('Metric `{}` created.'.format(m0['name']), 'success')
        flash('Metric `{}` created.'.format(m1['name']), 'success')
    except Exception as e:
        db.session.rollback()
        flash('Error: {0}'.format(e.message), 'danger')
    return redirect(url_for('services.index'))

kwek/templates/_formhelpers.html
{% macro render_field(field) %}
<div class="form-group">
  {{ field.label }}
  {{ field(class_="form-control",**kwargs)|safe }}
  {% if field.errors %}
    <ul class="errors">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
</div>
{% endmacro %}

kwek/templates/index.html
{% extends "layout.html" %}

<!-- <section class=".container-fluid content"> -->
{% block body %}


<!-- PATTERNFLY -->
  <script src="{{ url_for('static',filename='bower_components/c3/c3.min.js') }}"></script>
  <script src="{{ url_for('static',filename='bower_components/d3/d3.min.js') }}"></script>
      <div class="container-fluid container-cards-pf">
        <div class="row row-cards-pf">
          <div class="col-xs-6 col-sm-4 col-md-4">
          <div class="panel-heading">
            <h2>
              Dashboard
            </h2>
          </div>
          </div>
        </div>
        <div class="row row-cards-pf">
          <div class="col-xs-6 col-sm-4 col-md-4">
            <div class="card-pf card-pf-utilization">
  <h2 class="card-pf-title">
    Memory Usage
  </h2>
  <div class="card-pf-body">
    <p class="card-pf-utilization-details">
      <span class="card-pf-utilization-card-details-count">
        {{"{:.2f}".format( totals[metrics[0].tag] * metrics[0].conversion ) }}


      </span>
        <span class="card-pf-utilization-card-details-description">
          <span class="card-pf-utilization-card-details-line-1">Available</span>
          <span class="card-pf-utilization-card-details-line-2">of
          {{"{:.2f}".format( metrics[0].maxvalue * metrics[0].conversion ) }}
          {{metrics[0].unit}}</span>
        </span>
    </p>
    <div id="chart-pf-donut-5"></div>
    <div class="chart-pf-sparkline" id=""></div>

  </div>
</div>

          </div>
        </div><!-- /row -->
      </div><!-- /container -->
<!-- PATTERNFLY -->


<div class="row panel panel-default">
  <div class="panel-heading">Global Status <small>(total of {{projects|length}} projects)</small></div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Metric</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        {% for metric in metrics %}
        <tr>
          <td>{{metric.id}}</td>
          <td>{{metric.display_name}}</td>
          <td>
            {{"{:.2f}".format((totals[metric.tag])*metric.conversion)}}
            {{values[metric.tag]}}
            {{metric.unit}}
            {% if metric.maxvalue != 0 %}
            (<strong>
              {{"{:.2f}".format((totals[metric.tag] / metric.maxvalue)*100)}}%
            </strong> of {{"{:.2f}".format((metric.maxvalue)*metric.conversion )}} {{metric.unit}} )
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>

<div class="row panel panel-default">
  <div class="panel-heading">
    Your Projects
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          {% for metric in metrics %}
          <th>
            {{metric.display_name}}
          </th>
          {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for p in projects %}
          <tr>
            <td>{{loop.index}}</td>
            <td>
              <a href="{{url_for('kwek.stats', project=p['metadata']['name'])}}">
                {% if p['metadata']['annotations']['openshift.io/display-name'] %}
                  {{p['metadata']['annotations']['openshift.io/display-name']}}
                {% else %}
                  {{p['metadata']['name']}}
                {% endif %}
              </a>
            </td>
            {% for metric in metrics %}
              <td>
                {{"{:.2f}".format(
                  (values[p['metadata']['name']].avg[metric.tag]) * metric.conversion)
                }}
                {{ metric.unit }}
              </td>
            {% endfor %}
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>





<script>
  var c3ChartDefaults = $().c3ChartDefaults();

  var donutConfig = c3ChartDefaults.getDefaultDonutConfig('A');
  donutConfig.bindto = '#chart-pf-donut-5';
  donutConfig.color =  {
    pattern: ["#EC7A08","#D1D1D1"]
  };
  donutConfig.data = {
    type: "donut",
    columns: [
      ["Used", {{(totals[metrics[0].tag] * metrics[0].conversion)}}],
      ["Available", {{(metrics[0].maxvalue - totals[metrics[0].tag])* metrics[0].conversion}}]
    ],
    groups: [
      ["used", "available"]
    ],
    order: null
  };
  donutConfig.tooltip = {
    contents: function (d) {
      return '<span class="donut-tooltip-pf" style="white-space: nowrap;">' +
              Math.round(d[0].ratio * 100) + '%' + ' {{metrics[0].unit}} ' + d[0].name +
              '</span>';
    }
  };

  var chart1 = c3.generate(donutConfig);
  var donutChartTitle = d3.select("#chart-pf-donut-5").select('text.c3-chart-arcs-title');
  donutChartTitle.text("");
  donutChartTitle.insert('tspan').text("  {{"{:.2f}".format( totals[metrics[0].tag] * metrics[0].conversion ) }} ").classed('donut-title-big-pf', true).attr('dy', 0).attr('x', 0);
  donutChartTitle.insert('tspan').text("{{metrics[0].unit}} Used").classed('donut-title-small-pf', true).attr('dy', 20).attr('x', 0);

  var sparklineConfig = c3ChartDefaults.getDefaultSparklineConfig();
  sparklineConfig.bindto = '#';
  sparklineConfig.data = {
    columns: [
      ['%', 60, 55, 70, 44, 31, 67, 54, 46, 58, 75, 62, 68, 69, 88, 74, 88, 85],
    ],
    type: 'area'
  };

  var chart2 = c3.generate(sparklineConfig);
</script>

{% endblock %}
<!-- </section class=".container-fluid content"> -->

kwek/templates/insert_service.html
{% extends "layout.html" %}


{% block body %}

<ul>
{% for service in services %}
  <li>{{service}}</li>
{% endfor %}
</ul>

<ul>

{% for metric in metrics %}
  <li>{{metric}}</li>
{% endfor %}
</ul>


<form action="{{ url_for('kwek.insert') }}" method="post">
	<input type="text" name="service-name">
</form>

{% endblock %}

kwek/templates/layout.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Kwek Metrics</title>
  <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='css/style.css') }}">
    <!-- PatternFly Styles -->
  <link  href="{{ url_for('static',filename='bower_components/patternfly/dist/css/patternfly.min.css') }}" rel="stylesheet" media="screen, print">
  <link href="{{ url_for('static',filename='bower_components/patternfly/dist/css/patternfly-additions.min.css') }}" rel="stylesheet" media="screen, print">
</head>
<body>
  <!-- jQuery -->
  <script src="{{ url_for('static',filename='bower_components/jquery/jquery.min.js') }}"></script>
  <!-- Bootstrap -->
  <script src="{{ url_for('static',filename='bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
  <!-- PatternFly -->
  <script src="{{ url_for('static',filename='bower_components/patternfly/dist/js/patternfly.min.js') }}"></script>
  <header class="container page-header">
    <h1>Kwek Metrics <small>for OpenShift</small></h1>
  </header>

  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <section class="container errors">

      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
              <div class="errors__flashes row alert alert-{{category}}">
                <div class="col-md-4 offset-md-4">{{ message}}</div>
              </div>
            {% endfor %}
        {% endif %}
      {% endwith %}

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>

        <div class="col-md-4 offset-md-4">{{ message }}</div>

      </div>
    {% endif %}
    </section>
  {% endwith %}

  <section class="container">
    {% block body %}{% endblock %}
  </section>


  <footer class="container">
    <nav class="row navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{{ url_for('kwek.index')}}">Home</a></li>
            <li><a href="{{ url_for('services.index')}}">Manage Service Keys</a></li>
            <li><a href="{{ url_for('metrics.index')}}">Manage Metrics</a></li>
            <li><a href="{{ url_for('kwek.defaults')}}">Add Defaults</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </footer>

  <script src="{{ url_for('static',filename='js/index.js') }}"></script>
</body>
</html>

kwek/templates/stats.html
{% extends "layout.html" %}

{% block body %}


<h2>{{project}}</h2>

<p>Current status:</p>
{% for metric in metrics %}
  <li>
    {{metric.display_name}}:
    {% if values[metric.name][0] %}
      {{"{:.2f}".format((values[metric.name][0]['avg'])*metric.conversion)}}
    {% endif %}
    {{metric.unit}}
  </li>
{% endfor %}


<h3>Memory Usage</h3>
<svg id="memory" width="400" height="150"></svg>


<h3>CPU Usage</h3>
<svg id="cpu" width="400" height="150"></svg>


<h3>Network</h3>
<svg id="network" width="400" height="150"></svg>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://d3js.org/d3.v4.min.js"></script>
<script>
var WIDTH = 400,
    HEIGHT = 150,
    MARGINS = {
      top: 20,
      right: 20,
      bottom: 20,
      left: 100
    }

{% for metric in metrics %}
  var {{metric.name}} = {{values[metric.name]|tojson|safe}};
  var {{metric.name}}_vis = d3.select('#{{metric.name}}')
  {{metric.name}}_xRange = d3.scaleLinear().range([MARGINS.left, WIDTH - MARGINS.right]).domain([d3.min({{metric.name}}, function(d) {
    return d.end;
  }), d3.max({{metric.name}}, function(d) {
    return d.end;
  })]),
  {{metric.name}}_yRange = d3.scaleLinear().range([HEIGHT - MARGINS.top, MARGINS.bottom]).domain([d3.min({{metric.name}}, function(d) {
    return d.median/1024;
  }), d3.max({{metric.name}}, function(d) {
    return d.median/1024;
  })]),
  {{metric.name}}_xAxis = d3.axisBottom()
  .scale({{metric.name}}_xRange),
  {{metric.name}}_yAxis = d3.axisLeft()
  .scale({{metric.name}}_yRange);

  // Axis for {{metric.name}}
  {{metric.name}}_vis.append('svg:g')
  .attr('class', 'y axis')
  .attr('transform', 'translate(' + (MARGINS.left) + ',0)')
  .call({{metric.name}}_yAxis);

  // Define line function for {{metric.name}}
  var lineFunc = d3.line()
    .x(function(d) {
      return {{metric.name}}_xRange(d.end);
    })
    .y(function(d) {
      return {{metric.name}}_yRange(d.median/1024);
    })
    .curve(d3.curveLinear); // curveBasis

  {{metric.name}}_vis.append('svg:path')
  .attr('d', lineFunc({{metric.name}}))
  .attr('stroke', '{{metric.color}}')
  .attr('stroke-width', 2)
  .attr('fill', 'none');

{% endfor %}

</script>

{% endblock %}

kwek/templates/temp_stats.html
{% extends "layout.html" %}

<!-- <section class=".container-fluid content"> -->
{% block body %}

{% for metric in metrics %}
  <p>{{totals[metric.name]}}</p>
{% endfor %}
{% for total in totals %}
  <p>{{total}}</p>
{% endfor %}

{% endblock %}
<!-- </section class=".container-fluid content"> -->